cloudtools/awacs

awacs/ec2.py
Surprised this didn't already exist- figured I'd add it real fast.
=> Add EC2 specific ARN class

README.md
Updated module load
Return Principal instead of List
=> Update example to use new iam.ARN

CHANGELOG.md, awacs/helpers/trust.py, awacs/sts.py, setup.py, tests/test_helpers.py
https://github.com/boto/boto/blob/develop/boto/iam/connection.py#L29
Seems useful in awacs, not sure sts is the right place for it.
=> Helper for creating default AssumeRole policy

awacs/aws.py, tests/test_aws.py
=> Allow "*" Principals

awacs/route53.py, awacs/route53domains.py
- Also adds ARN & Action types
=> Add many new actions

awacs/elasticloadbalancing.py
Should probably do this for more of these, but just updating them as I run into them.
=> Add ARN & ELBAction

awacs/codecommit.py, awacs/codedeploy.py, awacs/elasticache.py
Update three services to the latest API as per AWS docs.
=> Updated ElastiCache, added CodeDeploy & CodeCommit

awacs/helpers/trust.py
From:
http://docs.aws.amazon.com/lambda/latest/dg/intro-permission-model.html
=> Lambda Trust Policy

awacs/ecr.py, examples/ecr.py
http://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_IAM_policies.html
=> EC2 Container Registry

awacs/ecs.py
=> Fix ECS full name

awacs/aws.py
http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html#Conditions_Null
=> Add Null Condition operator

awacs/helpers/trust.py
Fixes a minor comment typo and adds a helper method for CodeDeploy sts:AssumeRole
=> Add codedeploy trust helper

awacs/aws.py, tests/test_conditions.py
=> Add support for ForAllValues and ForAnyValues

awacs/helpers/trust.py
Pretty self-explanatory I think. See http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_IAM_role.html.
=> Add helper for get_ecs_task_assumerole_policy

awacs/helpers/trust.py, tests/test_helpers.py
We use a version of this internally at Remind and it's really useful.
=> Create generic assume role policy generator

awacs/aws.py, tests/test_aws.py
Fixes #58
http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html#Principal
=> Enable early validation of Principal strings

awacs/aws.py
Addresses ARN problem outlined in Issue #84
=> Generate valid ARNs for GovCloud and CN partitions of AWS in BaseARN

.travis.yml, awacs/helpers/trust.py, tests/test_helpers.py
See the link below for more info:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-permissions.html
=> Support for Lambda@Edge execution role

awacs/aws.py
=> Update aws.py Condition strings

awacs/aws.py, tests/test_aws.py
See aws-cloudformation/cfn-python-lint#1805
=> Do not hardcode partition if region isn't

MANIFEST.in, awacs/aws.py, scripts/generate_conditions.py
Thought I'd address #171 prior to release. 
@michael-k could you review and approve?
=> Add static definitions for Conditions to allow for better linting

awacs/__init__.py
=> Stop “caching” prop names

scrape/scrape.py
This should fix the scraper action (worked on my machine)
=> Update base url used by scraper
